version: '3.8'

services:
  strapi:
    image: node:18
    container_name: strapi
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run start"

  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
